### ISSUE TITLE
THIS IS SO BAD FUCKIGN IDIOT

### ISSUE THREAD

**Issue by L4CTOSE** [TheMemeSniper/athenarx#1]
YOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOT

**Comment by L4CTOSE** [comment]
YOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOTYOU ARE A IDIOT IDIOT

**Comment by TheMemeSniper** [comment]
fixed in 9ec2f63
